/*
 * Copyright (C) 2016 Michal Podhradsky, Cal Coopmans, michal.podhradsky@aggiemail.usu.edu
 * Utah State University, http://aggieair.usu.edu/
 *
 * This file is part of paparazzi.
 *
 * paparazzi is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * paparazzi is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with paparazzi; see the file COPYING.  If not, write to
 * the Free Software Foundation, 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

/**
 * @file firmwares/rotorcraft/guidance/guidance_simulink.h
 *
 * An interface to simulink autogenerated horizontal controller
 * Come to ICUAS2016 to learn more!
 *
 */

#ifndef GUIDANCE_SIMULINK_H
#define GUIDANCE_SIMULINK_H

#include "std.h"

// include the module we want - eventually make configurable in the defines...
#include "modules/simulink/test1.h"


extern void guidance_simulink_enter(void);
extern void guidance_simulink_run(void);

#endif /* GUIDANCE_SIMULINK_H */
