#! /usr/bin/env python

#  Copyright (C) 2013 Felix Ruess <felix.ruess@gmail.com>
#
# This file is part of Paparazzi.
#
# Paparazzi is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# Paparazzi is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Paparazzi; see the file COPYING.  If not, write to
# the Free Software Foundation, 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.
#

from __future__ import print_function
import sys
import os
import subprocess
from optparse import OptionParser, OptionGroup, OptionValueError


def main():
    usage = "usage: %prog -a <ac_name> -t <sim_type> [sim arguments]\nRun %prog --help to list the options."
    parser = OptionParser(usage)
    parser.add_option("-a", "--aircraft", dest="ac_name",
                      action="store", metavar="NAME",
                      help="Aircraft name to use")
    # get environment
    paparazzi_home = os.environ['PAPARAZZI_HOME']
    if not paparazzi_home:
        paparazzi_home = os.getcwd()
    print("Using "+paparazzi_home+" as Paparazzi home dir.")
    (options, args) = parser.parse_args()
    if not options.ac_name:
        parser.error("Please specify the aircraft name.")
    ac_dir = os.path.join(paparazzi_home, "var", "aircrafts", options.ac_name)
    print("HITL launcher v 0.1")
    print("Launching "+ac_dir)
    simhitl = os.path.join(ac_dir, "hitl", "simhitl")
    # start the simulator, replacing this process
    os.execv(simhitl, [simhitl])

if __name__ == "__main__":
    main()
